# Generated by Django 6.0.4 on 2026-05-12 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_designation_to_doctor'),
        ('core', '0003_doctor_profile_and_report_sent'),
    ]

    operations = [
    ]
